### ISSUE TITLE
Add new method destroy()

### ISSUE THREAD

**Issue by vuhrmeister** [funkensturm/ember-local-storage#11]
In addition to the `reset` method I think it would be cool to be able to completely remove the data from the storage by calling `destroy()` or something.

**Comment by fsmanuel** [comment]
@vuhrmeister `destroy()` isn't a good name because it would destroy the `Ember.Object` but i can see your point. I guess `clear` would be a good one. 

I think all we need is:
```js
// https://github.com/funkensturm/ember-local-storage/blob/master/addon/mixins/storage.js
clear: function() {
  delete this.storage()[this.get('storageKey')];
}
```
and some tests. Do you want to take a stab at that?

**Comment by vuhrmeister** [comment]
Ok, you're right. `destroy()` is not good. But `clear()` is just fine.

Yes, I can add that feature as soon as I come to that point.

**Comment by fsmanuel** [comment]
@vuhrmeister i implemented `.clear()` can you review?

**Comment by vuhrmeister** [comment]
Yes. Will have a look at it tomorrow and test it as well.

**Comment by vuhrmeister** [comment]
Looks fine and works!
