### ISSUE TITLE
Adding method to check whether model is new

### ISSUE THREAD

**Issue by vuhrmeister** [funkensturm/ember-local-storage#12]
A method like `isNew` or `isInitialData`(I'm not that creative) to check whether the model is modified or in original state.

**Comment by fsmanuel** [comment]
@vuhrmeister Can you elaborate on a particular use case? That would make it more easy to figure out what kind of life cycle infos/hooks we need.

**Comment by vuhrmeister** [comment]
Yes, sure.

In an order process I have an `basket` model, where I store data like articles and some order details.
In several places I have to check wether the user has changed the data or if the data are the initial one. I don't want to check each attribute on wether it was changed or not.

**Comment by fsmanuel** [comment]
You only need the information if it's the initial data? That should be easy. I'll implement it in the next days.

**Comment by vuhrmeister** [comment]
Correct, I only need that information. Sounds good (y)

**Comment by vuhrmeister** [comment]
awesome, thx :)

**Comment by vuhrmeister** [comment]
It seems there is an issue with that implementation.
I just installed the master branch and now I have the following issue:

Calling reset on **some** objects does not have any effect. It doesn't change in local storage.
However, installing version 0.0.5 again fixes the issue.

But still, with 0.0.5 it resets only objects, not arrays.

I tried hard to find out what's the issue. I can't tell you. I even created two models with the exact same structure but different key and location. It's really strange.

**Comment by fsmanuel** [comment]
@vuhrmeister i know why. will fix it by merging the `.clear()` PR

**Comment by fsmanuel** [comment]
@vuhrmeister can you try again with master?

**Comment by vuhrmeister** [comment]
Great, works!

But still reset on array does not work.

**Comment by fsmanuel** [comment]
I'll have a look.
