### ISSUE TITLE
sessionStorage adapter/serializer?

### ISSUE THREAD

**Issue by schickm** [funkensturm/ember-local-storage#120]
Thanks for the awesome library!

I found myself wanting to use sessionStorage for ember models rather then localStorage.  I'm wondering what you'd think about supporting an adapter/serializer for sessionStorage in the library?  Or, just making the existing adapter a little more flexible for accommodating the change to sessionStorage.  

Below is what I had to do to make my own extension of the existing adapter (the serializer required no changes).  As you can see I'm overriding some internal properties of the class, which makes me a little leery as the library internals could change at any time.

I'm happy to provide a pull request for either if you're interested.

 ```javascript
import Ember from 'ember';
const {
  get,
} = Ember;

import LocalStorageAdapter from 'ember-local-storage/adapters/adapter';
import { getStorage } from 'ember-local-storage/helpers/storage';
import StorageArray from 'ember-local-storage/session/array';

export default LocalStorageAdapter.extend({
    _storage: getStorage('session'),

    _getIndex(type) {
        const indices = get(this, '_indices');

        if (!indices[type]) {
            indices[type] = StorageArray
            .extend({ _storageKey: 'index-' + type })
            .create();
        }

        return indices[type];
    },
});
```

**Comment by fsmanuel** [comment]
Hey @schickm sorry for the late reply.
Interesting. Do you use it for a demo or why do you need only the sessionStorage?

I'm happy to accept a PR!

**Comment by schickm** [comment]
No problem, we're all busy people.  

For an application I'm working on, we have some data that we want to disappear when the user closes their browser window, and some data that we want to stick around.  So we use a mix of local and session storage.

So do you want the PR to just have a separate adapter like the one above?  Then just add a little note in the documentation about the special case?  I worry that it might be a little confusing for first time users that the adapter for localStorage is `ember-local-storage/adapters/adapter`, but the adapter for sessionStorage would be something like `ember-local-storage/adapters/session-storage-adapter.

I propose that we move the code from `ember-local-storage/adapters/adapter` to `ember-local-storage/adapters/local-storage-adapter`.  Then have `ember-local-storage/adapters/adapter` just export the new `local-storage-adapter`  along with displaying a deprecation notice for the next couple releases.  Then put the sessionStorage adapter at `ember-local-storage/adapters/session-storage-adapter`.

I assume issuing deprecation notices from ember addons is a thing?  It's not just something internal to ember?

Sound good?

**Comment by fsmanuel** [comment]
@schickm I like that you care about the structure!

My preferred structure would be:
`ember-local-storage/adapters/adapter` exports `ember-local-storage/adapters/local`
`ember-local-storage/adapters/local` the old adapter
`ember-local-storage/adapters/session` your implementation

That way we only have to change the readme and add the two options of `local` and `session` and it's still backward compatible without any deprecations.

The next step would be to refactor `local` and `session` and let them inherit form a `base` adapter that contains all the common logic. I propose to open a new issue for the refactoring and stick to your implementation for the feature PR.

**Comment by schickm** [comment]
@fsmanuel Thanks man, got to keep that structure in line!

Sounds good, no need for deprecation.  I'll hopefully be able to get to this in the next few days and have it up for your review.
