### ISSUE TITLE
Could not find module `ember-local-storage/adapters/local`

### ISSUE THREAD

**Issue by zequeira** [funkensturm/ember-local-storage#152]
Hi, 

I'm trying to configure "ember-local-storage" to work with "ember-data" and I can not make it work, maybe I'm not getting your explanations on the Readme.

Could you provide some more information on how is "ember-local-storage" interacting with "ember-data"??
Is it like if I'm already using "ember-data" and then I integrate "ember-local-storage" then the model goes automatically to localStorage??
I have done this two instructions from you:
```
If you already use Ember Data for non LocalStorage models you can use a per type adapter and serializer.

// app/adapters/post.js
export { default } from 'ember-local-storage/adapters/local';
// or export { default } from 'ember-local-storage/adapters/session';

// app/serializers/post.js
export { default } from 'ember-local-storage/serializers/serializer';
```
and have got the error:
```
Uncaught Error: Could not find module `ember-local-storage/adapters/local` imported from ...
```

What I want to accomplish is that, I have a few JSON objects that I give as a model to a template and I want to load those JSON objects in localStorage and connect that with "ember-data".

Thanks in advance for the help,
Best.

**Comment by fsmanuel** [comment]
@zequeira Sorry! That was my fault. I forgot to publish the new version `1.3.0`. Now it's out and use `localStorage` and `sessionStorage` adpaters. Just update the the addon to the new version and then it should work.

Reopen the issue, if it doesn't solve the problem.

**Comment by zequeira** [comment]
Hi @fsmanuel 
Thank you very much for your quick answer. The error is gone, but I'm still haven't been able to have together "ember-data" + "ember-local-storage" working.

I assume that I have to import my JSON object (which is not complaint with the JSON API) into the localStorage, using your "this.store.importData(file.data);" approach. but is not working. I tried:
```
this.store.importData(jsonObject, {json:true, truncate:false  })
```
and is not working.

It seems that in order to use: "this.store.importData" the jsonObject has to be JSON API complaint ??

Could you please provide me or point me to some examples to see how "ember-data" and "ember-local-storage" should work together??

Thanks in advance.

**Comment by fsmanuel** [comment]
@zequeira You should have a ember-data model that uses the ember-local-storage adapter.

Lets say you have a `app/models/post` model then you need a `app/adapters/post` adapter and a `app/serializers/post` serializer:

```js
// app/adapters/post.js
export { default } from 'ember-local-storage/adapters/local';

// app/serializers/post.js
export { default } from 'ember-local-storage/serializers/serializer';
```

Now you can create your model in the router and use the normal ember-data api to find and manipulate your record:

```js
let post = this.get('store').createRecords({
  title: 'Headline',
  body: 'Some text'
});

post.save();
```

Ping me on slack if you have more questions.

**Comment by fsmanuel** [comment]
@zequeira can I close the issue?

**Comment by zequeira** [comment]
@fsmanuel Sorry for the silence, your suggestion before didn't work. I'll ping you in stackoverflow ;)
