### ISSUE TITLE
Ember-data dependency

### ISSUE THREAD

**Issue by ssured** [funkensturm/ember-local-storage#154]
It seems the project depends on Ember-data (addon/adapters/base.js imports DS). It would be wonderful if Ember Data was an optional dependency.

Thanks for open sourcing your lib, it works like a charm!

**Comment by fsmanuel** [comment]
@ssured ember-data is not a dependency. I check if ember-data is installed and remove the ember-data related files on [build](https://github.com/funkensturm/ember-local-storage/blob/master/index.js#L50-78).

If that is not the fact it is a bug and we should investigate it.

**Comment by ssured** [comment]
You are right, but...

I get a

```
loader.js:218 Uncaught Error: Could not find module `ember-data` imported from `ember-local-storage/initializers/local-storage-adapter`missingModule @ loader.js:218findModule @ loader.js:229Module.findDeps @ loader.js:169findModule @ loader.js:232Module.findDeps @ loader.js:169findModule @ loader.js:232requireModule @ loader.js:18(anonymous function) @ index.js:18exports.default @ index.js:15(anonymous function) @ app.js:13Module.exports @ loader.js:122requireModule @ loader.js:21(anonymous function) @ app-boot.js:4
```
 error when running the app without ember data.

What causes this is that the `node_modules/ember-data` folder still exists, even though `package.json` has the reference to `ember-data` removed.

Manually removing the `node_modules/ember-data` folder solved the issue.

**Comment by fsmanuel** [comment]
@ssured Ah ok. Now we have an issue to point people if they experience the same problem. Thanks!
