### ISSUE TITLE
.reset() does not work for arrays

### ISSUE THREAD

**Issue by fsmanuel** [funkensturm/ember-local-storage#17]

**Comment by vuhrmeister** [comment]
One interesting point is: The data in local storage is not removed but the implementation of the StorageArray returns an empty array or 0 for `length`!

**Comment by fsmanuel** [comment]
good to know.

**Comment by fsmanuel** [comment]
@vuhrmeister can you verify that master is working?

**Comment by fsmanuel** [comment]
@vuhrmeister i'll cut a new release if master is working now. can you confirm?

**Comment by vuhrmeister** [comment]
Sorry, I wasn't available the weekend. Will check it now.

**Comment by vuhrmeister** [comment]
Yay, works perfectly (y)

**Comment by fsmanuel** [comment]
great! thanks for all your feedback and testing. i'll release tonight.

**Comment by vuhrmeister** [comment]
yw - I have to thank you for the quick implementation!

**Comment by fsmanuel** [comment]
0.0.6 released
