### ISSUE TITLE
Option for a project prefix to enhance localStorage specificity

### ISSUE THREAD

**Issue by csprocket777** [funkensturm/ember-local-storage#172]
Here's my use case.

I am making something that reads in a particular sheet from Smartsheet (smartsheet.com). 
I am providing the ability to specify which sheet via a route parameter (sheet/1234567).
I am displaying the data to the user and allowing them to vote on individual rows in the data. I don't want to create accounts or store user IDs back into the smartsheet, so instead I'm storing the sheetID+rowID as an entry into an array using ember-local-storage to capture their vote and prevent repetitive votes. Right now I have a single level array that might encompass many many different sheets. I'd rather have a local storage object that is specific to my application and to the particular sheet that is being recorded. 

Current State: "storage:idea-votes = array()"
Desired State: "[appname or project prefix+storage]:idea-votes = { sheetID: array() }"
OR
Desired State: "[computed property+storage]:idea-votes = array()" and I could change this based on the route parameter that was read in.

**Comment by fsmanuel** [comment]
@csprocket777 There is a way to do that but it is still experimental: [`storageFor`](https://github.com/funkensturm/ember-local-storage#storagefor-options). Look at the second argument `model`. If you provide an object with a `modelName` and `id` it will compute a key based on that object.

`storageFor('idea-votes', {modelName: 'sheet', id: 12})` should result in `storage:idea-votes:sheet:12`

Let me know if it solves your problem.

**Comment by fsmanuel** [comment]
@csprocket777 Can I close the issue?
