### ISSUE TITLE
Cannot set values on deep neested properties

### ISSUE THREAD

**Issue by tmaynx** [funkensturm/ember-local-storage#20]
Hi everybody,

I've a object that looks this:
```
{
  details: {
    address: {
      first: {...},
      second: {...}
    }
  }
}
```

It is easily possible to set values on the first level (eg. details.address), but there's no chance to change values on a deeper level (eg. details.address.first).

Ember recognizes the change an show the right value, if I render the output on my template. But the local storage item shows no change.

Any suggestions to solve this issue?

**Comment by fsmanuel** [comment]
How do you set the deep values?
Something like that: `settings.set('details.address.first', {street: 'Somestreet'})`

**Comment by tmaynx** [comment]
Almost this way.
I'm using: ´´´settings.set('details.address.first', addressObj)´´´. The variable "addressObj" contains an object address with multiple properties.

**Comment by fsmanuel** [comment]
What is your `initialContent`? I'll add a test and than fix it.

**Comment by tmaynx** [comment]
Here is an extract from my code with replaced property names:

```
import StorageObject from 'ember-local-storage/local/object';

export default StorageObject.extend({
  storageKey: 'details',
  initialContent: {
    address: {
      first: null,
      second: null,
      anotherProp: null
    }
  }
});
```

Sounds great, thank you for help!

**Comment by fsmanuel** [comment]
I added a test but it's not failing.
The [model](https://github.com/funkensturm/ember-local-storage/blob/master/tests/dummy/app/models/nested-object.js)
The [test](https://github.com/funkensturm/ember-local-storage/blob/master/tests/unit/object-test.js#L21)

Can you verify that you use it the same way?

**Comment by fsmanuel** [comment]
It should be:
`details.set('address.first', addressObj);`

details should not be in the set path.

**Comment by fsmanuel** [comment]
@tmaynx did it work?

**Comment by tmaynx** [comment]
Sorry for my late answer, didn't saw your response.

Yes, it works this way, thank you for explanations. Thought it would be possible to set deeper paths as first arguments in the `set`method, but this works fine for me.

Thank you for quick answers!
