### ISSUE TITLE
Ember 2.10.0 has message DEPRECATION: ember-getowner-polyfill

### ISSUE THREAD

**Issue by palamike** [funkensturm/ember-local-storage#211]
Hi,

I already upgrade to Ember 2.10.0 and found warning DEPRECATION: ember-getowner-polyfill.

Here is the full message 

`DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]`

I see the source code and found that 

FIle : ember-local-storage/addon/helpers/storage.js  is still using "import getOwner from 'ember-getowner-polyfill';" 

Please help to fix.

**Comment by fsmanuel** [comment]
@palamike I'll have a look next week.

**Comment by planetexpress69** [comment]
@palamike Just remove the line "import getOwner from 'ember-getowner-polyfill';" and use 
"const owner = Ember.getOwner(context);"...

**Comment by palamike** [comment]
Hi @planetexpress69 , I already did that. just want to inform project owner. :)

**Comment by planetexpress69** [comment]
Pull request, then?

--

**Comment by palamike** [comment]
Hi @planetexpress69 , Next time I will learn how to create the pull request. I never create before. Thank You 👍

**Comment by fsmanuel** [comment]
@palamike @planetexpress69 to stay backwards compatible we can not just remove the polyfill. I'll fix it.

**Comment by fsmanuel** [comment]
@palamike @planetexpress69 I released `1.3.4` that removes the deprecation and a deprecation for ember-data canary.
