### ISSUE TITLE
restoring array of objects from local storage and pushMany to memory storage

### ISSUE THREAD

**Issue by sunil-shrestha** [funkensturm/ember-local-storage#22]
I was trying to restore array of objects from local storage and pushMany to memory storage when application is ready. It seems that the object in the array does not include id, due to which i was not able do so. Would it be possible to include id for each object while pushing to local storage? Or is there some solution to this kind of cases?

**Comment by fsmanuel** [comment]
@sunil-shrestha i guess what you are looking for is an ember-data adapter.
I have an experimental branch with an [adapter](https://github.com/funkensturm/ember-local-storage/tree/feat/adapter). I plan to release it this week.

**Comment by sunil-shrestha** [comment]
Yeap, adapter would be great. Thanks !

**Comment by fsmanuel** [comment]
https://github.com/funkensturm/ember-local-storage/issues/21

**Comment by fsmanuel** [comment]
@sunil-shrestha can I close the issue?

**Comment by sunil-shrestha** [comment]
Yes, Thanks for your help !
