### ISSUE TITLE
Feature Request: restore nested ember object. 

### ISSUE THREAD

**Issue by Kilowhisky** [funkensturm/ember-local-storage#23]
It would be great if the addon had the ability to restore full-blown ember objects that it has as properties. For instance an object that has nested sub objects of a different type. Right now it can restore nested objects but the objects restored are POJOs and because of that property changes on them cannot be observed/triggered. 

Would it be as simple as storing an object type key along with it and then using the type key to instantiate a new version of the object and feeding it the POJO of the values? 

I don't know if this falls under the category of an adapter or can be worked in with the object/array functionality that this addon provides.

**Comment by fsmanuel** [comment]
@Kilowhisky the question is how deep do you want to nest? Is there a limit or nor. Can you elaborate on your use case? Maybe the upcoming [adapter](https://github.com/funkensturm/ember-local-storage/issues/21) can solve your problem.

**Comment by Kilowhisky** [comment]
I would say practically a limit probably shouldn't exist. Here is my use case.

I have my main object that represents the state for a page.  The main object contains an array of state objects for sub-tables. There can be many tables shown or 1 table shown. Each table shown can have sub-objects that represent sub-states. Ever object in the chain needs to be able to be tracked via. get/set properties.  

```
{
  tablesShown: [{
      tableId: 1,
      sortBy: 'property', 
      orderBy: 'property'
      editing: {
           id: 1,
           textField1: 'this is edited text that is staying around'
       }
 },
 etc...
]
}
```

I've actually previously been using an adapter for this job so it may very well be that will suffice just fine.

**Comment by fsmanuel** [comment]
@Kilowhisky I merged #19 and master now provides an ember-data adapter.

See [Adapter & Serializer](https://github.com/funkensturm/ember-local-storage#adapter--serializer) in the README.

**Comment by fsmanuel** [comment]
@Kilowhisky I added documentation for the models: https://github.com/funkensturm/ember-local-storage#model

**Comment by fsmanuel** [comment]
@Kilowhisky can I close the issue?
