### ISSUE TITLE
Update data to local storage

### ISSUE THREAD

**Issue by absemetov** [funkensturm/ember-local-storage#232]
Local storage update only when I add or removeObject
When set data Ember.set(item, "count", count_goods), LS update only after addObject()

**Comment by fsmanuel** [comment]
@absemetov you can not use `Ember.set` you need to use `item.set('count', count_goods)`.
I overwrite the `set`/`get` of the object/array not the `Ember.set`. Hope that helps.

**Comment by absemetov** [comment]
var item = this.get('cartStorage.content').findBy('id', product.get('id'));

Error: item.set is not a function

**Comment by fsmanuel** [comment]
Try this (without `content` in the key):

```js
var item = this.get('cartStorage').findBy('id', product.get('id'));
item.set('count', count_goods);
```

**Comment by absemetov** [comment]
Uncaught TypeError: item.set is not a function

**Comment by absemetov** [comment]
cartStorage is Array

**Comment by fsmanuel** [comment]
@absemetov ah you have nested data. that doesn't work. As a workaround you can delete it from the array, modify it and readd it to the array.

**Comment by fsmanuel** [comment]
@absemetov i'm closing this. Reopen if you need more help
