### ISSUE TITLE
#219 breaks importData

### ISSUE THREAD

**Issue by jlblcc** [funkensturm/ember-local-storage#233]
PR #219 breaks the importData function. The localstorage index is not updated until a browser refresh due to _indices on the adapter being set as a computed property(_indices does not reflect the current localstorage state). You can reproduce this by running the demo locally and trying to import a file like this [my-data.txt](https://github.com/funkensturm/ember-local-storage/files/794522/my-data.txt). Changing _indices back to a POJO fixes the issue, but will cause problems with tests as noted in the PR.

**Comment by fsmanuel** [comment]
@jlblcc oh that is sad! @bendemboski do you have any idea how we tackle that?

**Comment by bendemboski** [comment]
Whoops! #234 fixes the issue.

**Comment by jlblcc** [comment]
Can we get #234 merged and a patched version released? I'd like to use some of the features from master, but this is blocking. Thanks!

**Comment by fsmanuel** [comment]
@jlblcc sorry for the delay. I'll release today!

**Comment by fsmanuel** [comment]
@jlblcc how are you using the import/export? Via store or adapter? I think about deprecating the use via adapter...

**Comment by fsmanuel** [comment]
@jlblcc published `1.3.6`

**Comment by jlblcc** [comment]
@fsmanuel I'm using import/export via store(`this.store.importData`). So no worries re: adapter deprecation.

Thanks for the release (and the addon)!
