### ISSUE TITLE
Editing an object in an array

### ISSUE THREAD

**Issue by skaterdav85** [funkensturm/ember-local-storage#24]
Say you have an array of objects. How can I edit one of those objects given the index? I've tried this:

```js
this.get('stuff').objectAt(1).set('sport', 'hockey');
```

I get an error that says set is not a function.

**Comment by fsmanuel** [comment]
@skaterdav85 the object at index is a POJO and not an `Ember.Object`. The array isn't really useful for objects. It's more a list to add and remove simple items from.
Can you elaborate on your use case? Maybe the upcoming [adapter](https://github.com/funkensturm/ember-local-storage/issues/21) can solve your problem.

**Comment by skaterdav85** [comment]
Basically I was thinking of using this as a replacement for the [local storage adapter](https://github.com/kurko/ember-localstorage-adapter) because that project doesn't look maintained anymore and the build has been showing failing for awhile now. My use case was to make a shopping cart where order-items is an array of objects and each order-item object could be edited, such as editing the quantity. Definitely looking forward to seeing your adapter!

**Comment by fsmanuel** [comment]
@skaterdav85 I merged #19 and master now provides an ember-data adapter.

See [Adapter & Serializer](https://github.com/funkensturm/ember-local-storage#adapter--serializer) in the README.

**Comment by skaterdav85** [comment]
awesome! thanks!

On Mon, Aug 24, 2015 at 9:40 AM, Manuel Wiedenmann <notifications@github.com
> wrote:

> @skaterdav85 <https://github.com/skaterdav85> I merged #19
> <https://github.com/funkensturm/ember-local-storage/pull/19> and master
> now provides an ember-data adapter.
>
> See Adapter & Serializer
> <https://github.com/funkensturm/ember-local-storage#adapter--serializer>
> in the README.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/funkensturm/ember-local-storage/issues/24#issuecomment-134294175>
> .
>



-- 
David

**Comment by fsmanuel** [comment]
@skaterdav85 I added documentation for the models: https://github.com/funkensturm/ember-local-storage#model

**Comment by fsmanuel** [comment]
@skaterdav85 can I close the issue?
