### ISSUE TITLE
Add a resetToInitialState method

### ISSUE THREAD

**Issue by dja** [funkensturm/ember-local-storage#249]
From my understanding, you would need to call clear() and reset() on a StorageObject to reset it to its initial state.. Is there a more optimal way we could do this in just one method?

**Comment by fsmanuel** [comment]
@dja just `reset()` should work. Why do you think that you need `clear()` before?

**Comment by dja** [comment]
Awesome, nevermind that then - I thought clear was doing something separate from how it's explained in the readme as removing content from xStorage.
