### ISSUE TITLE
Changes on object in array are not saved

### ISSUE THREAD

**Issue by vuhrmeister** [funkensturm/ember-local-storage#25]
Hi, it's me again :)

I'm not sure if that's by purpose or if there is still a bug. At least it reminds me on https://github.com/funkensturm/ember-local-storage/issues/17.

My scenario is that I have an array of objects which will change from time to time.
It is important that the item stays at the original index why I can't just remove and add id again. 

`items` is an array and look like:
```
[
   {id: 1, count: 3}, 
   {id: 2, count: 5}
]
```

Use case as follows:
```
items.arrayContentWillChange();

var item = items.objectAt(1);
item.count = 9;

items.arrayContentDidChange();
```

I have to trigger `arrayContentDidChange` so that the observers can react on the change and rerender the updated count value.

So when having this setup the value of the Array does change, but NOT the item in local storage.

**Comment by fsmanuel** [comment]
@vuhrmeister in your use case we could save on `arrayContentDidChange()` but it looks more like you want to have a real model and an adapter. I have to add docs and some cleanup before I can release the adapter. I'll ping here as soon as I release.

**Comment by fsmanuel** [comment]
https://github.com/funkensturm/ember-local-storage/issues/21

**Comment by vuhrmeister** [comment]
Well, not necessarily … but ok, will wait for your adapter, maybe I will switch then. Right now it's working since I have implemented a small workaround.

**Comment by fsmanuel** [comment]
I merged #19 and master now provides an ember-data adapter.

See [Adapter & Serializer](https://github.com/funkensturm/ember-local-storage#adapter--serializer) in the README.

**Comment by fsmanuel** [comment]
@vuhrmeister I added documentation for the models: https://github.com/funkensturm/ember-local-storage#model

**Comment by vuhrmeister** [comment]
Thx, I'm already checking whether or where I could use it. Looks nice anyway.
