### ISSUE TITLE
chrome.storage.local

### ISSUE THREAD

**Issue by wmlele** [funkensturm/ember-local-storage#255]
How hard you think it would  be to adapt ember-local-storage to be able to also support chrome.storage.local? Apart for for the API changes, my understanding is that the chrome storage is intrinsically asynchronous, vs the synchronous window.localStorage.
I could give it a shot, but any input will be appreciated.

**Comment by fsmanuel** [comment]
@wmlele Sorry for the late response. If I'm correct there is a localForage driver: https://github.com/esphen/localforage-webExtensionStorage-driver

I would prefer to get a localForage implementation ready (#153) that allows to use [custom drivers](https://github.com/localForage/localForage/wiki/Custom-Drivers).

Right now I don't have the time to do it. There is a preliminary TODO list to get localForage in (https://github.com/funkensturm/ember-local-storage/issues/153#issuecomment-229517492).

If you have time you can take a shot. I'm happy to help.

**Comment by fsmanuel** [comment]
Superseeded by https://github.com/funkensturm/ember-local-storage/issues/337
