### ISSUE TITLE
_resetStorages() Documentation

### ISSUE THREAD

**Issue by Houndsto0th** [funkensturm/ember-local-storage#258]
We've been wrestling with state bleeding between acceptance tests when one of our engineers came across the `_resetStorages()` helper that you use in the test suite for the addon itself. I would think this should probably be in the documentation as a way to consistently reset the value of local storage variables in Acceptance tests in a `beforeEach()` block since other approaches like `window.localStorage.clear()` don't work.

**Comment by fsmanuel** [comment]
@Houndsto0th I'm happy to accept a PR that provides a test helper/function that uses `_resetStorages()` and updates the docs!

**Comment by fsmanuel** [comment]
Closed via #296
