### ISSUE TITLE
Dynamic property in the initialContent object

### ISSUE THREAD

**Issue by tonkonogov** [funkensturm/ember-local-storage#26]
Hi, I use a i18n package for ember and I specified the default value for locale in env.js file.

Now I want to store the current language in localStorage, but I want to avoid copy-paste for the default value and keep it only in env.js. Something like this:

    initialContent: {
       locale: %default_value%
    }

 I can't use `this.get('i18n.defaultLocale')` (a usual way) for that, since it's an array declaration and `this` cannot be used on high-level. `Ember.computed` works but it stores the whole Ember object.

How can I set a dynamic value in this case?

**Comment by fsmanuel** [comment]
@tonkonogov you can import your env.js

```js
import StorageObject from 'ember-local-storage/local/object';
import env from 'appPrefix/env';

export default StorageObject.extend({
  storageKey: 'something',
  initialContent: {
    locale: env.get('i18n.defaultLocale')
  }
});
```

**Comment by tonkonogov** [comment]
Yeap, it was a pretty obvious solution that I missed. 

`env.get` doesn't work for me, but direct addressing works fine - `env.i18n.defaultLocale`.

Thanks for quick help!

**Comment by fsmanuel** [comment]
:+1:
