### ISSUE TITLE
initialState properties not defined on clean boot

### ISSUE THREAD

**Issue by mwpastore** [funkensturm/ember-local-storage#267]
I've got a bit of a head-scratcher. I have a StorageObject with an initialState that's being injected into a service. When the app first boots, I don't see the initialState properties in localStorage in the console, and they're undefined if I `get` them. Other properties that are manually `set` look and work just fine. When I refresh the browser tab, the initialState properties appear in localStorage and become usable. It's almost as if there's a race condition between the service and the StorageObject definition that's influenced by whether or not the localStorage key exists when the app boots. Any thoughts?

UPDATE: Hrrm, it appears to be available during the service's `init` hook, but not from within an ember-concurrency `task` entangled with the service. The plot thickens...

**Comment by fsmanuel** [comment]
@mwpastore thanks for reporting. Can you provide a sample app? Would like to dig into it.

**Comment by fsmanuel** [comment]
@mwpastore any news on it?
