### ISSUE TITLE
Storages can't have dependencies injected in Ember@2.14

### ISSUE THREAD

**Issue by kswilster** [funkensturm/ember-local-storage#268]
The following error is thrown when attempting to inject dependencies into a storage in Ember@2.14. I'm not sure if this was explicitly supported before, but it has functioned correctly until at least version 2.12. I can't demonstrate this on ember-twiddle at the moment (it supports up to Ember@2.12) but I've created a [simple demo to illustrate this effect](https://github.com/kswilster/localstorage-injection-demo). Allowing dependency injection again should be as simple as setting the owner of each `StorageFactory` right around [here](https://github.com/funkensturm/ember-local-storage/blob/master/addon/helpers/storage.js#L112)

![image](https://user-images.githubusercontent.com/1093185/29047190-9b3c0e90-7b98-11e7-90a1-91fc47a3d5ae.png)

**Comment by fsmanuel** [comment]
@kswilster Thanks for reporting. I'll have a look at it as soon as I have some cycles.

ref: https://github.com/stefanpenner/ember-state-services/commit/11016b0b547456c62f46d91b2d83606bb4c33119#diff-418a1659ad37efb36c19f41815e06d96R64

**Comment by fsmanuel** [comment]
@kswilster it took some time but this problem should be resolved with the new version.
