### ISSUE TITLE
storageFor() in route's model hook

### ISSUE THREAD

**Issue by cjwyatt** [funkensturm/ember-local-storage#269]
Hi, I was wondering if it's not possible to use storageFor in the model hook in a route. When I tried doing:

`return {            
  cart: storageFor('cart')
};`

It seems to work until I access the cart property in the template and then I get:

`TypeError: Cannot read property 'registerOptionsForType' of undefined
    at createStorage (storage.js:105)
    at Object.<anonymous> (storage.js:65)
    at ComputedPropertyPrototype.get (ember.debug.js:25794)
    at get (ember.debug.js:25102)
    at NestedPropertyReference.compute (ember.debug.js:21869)
    at NestedPropertyReference.value (ember.debug.js:21679)
    at ArrayIterable.iterate (ember.debug.js:21421)
    at IterationArtifacts.isEmpty (ember.debug.js:568)
    at IterablePresenceReference.value (ember.debug.js:7942)
    at ReferenceCache.initialize (ember.debug.js:490)`

It works fine in components. Is there no way of using it from a route's model hook?

**Comment by fsmanuel** [comment]
@cjwyatt You need to use `storageFor` in the route and then access it in the model hook. Think of `storageFor` as a computed property (it actually is) that needs the right `this`. In your case the route.

```js
import Route from 'ember-route';
import { storageFor } from 'ember-local-storage';

export default Route.extend({
  cart: storageFor('cart'),

  model() {
    return { cart: this.get('cart') };
  }
});
```

**Comment by cjwyatt** [comment]
Ah OK, that makes sense. I've got that working so it displays the content set in initial state now. Though I notice it doesn't seem to persist changes when I do:

```javascript
var model = this.modelFor(this.routeName);
model.content.replace(index, 1, ['Testing']);
```

Is there something I need to call to persist such changes?

**Comment by fsmanuel** [comment]
@cjwyatt you should not modify the content and just use `.addObject` or `.removeObject`. It's a proxy object and the `content` is somewhat privat (the proxied content).
Can you post more of your example so I can better help you?

**Comment by fsmanuel** [comment]
@cjwyatt can I close the issue?

**Comment by cjwyatt** [comment]
Hey, yeah, sorry, I completely forgot about this issue.
