### ISSUE TITLE
storing to local-storage with addObjects becomes very slow when records grow

### ISSUE THREAD

**Issue by sunil-shrestha** [funkensturm/ember-local-storage#27]
I was trying to store to local storage (around 500 records) and realised that the storing process is really slow (around 15 seconds). Here is my use case.

    var records = this.store.peekAll(modelName).map(function (record) {

	    return { id: record.id, content: record } ;

    });

    this.get('arrayOfRecords').addObjects(records);

However, when i use 

    this.get('arrayOfRecords').addObject(records);

The storing process completed in a second but updating to local storage did not work anymore.
Any idea how we can accomplish this?
Also, it would be nice to have some method to replace initial content.

**Comment by fsmanuel** [comment]
@sunil-shrestha what version of ember-data are you using? I merged https://github.com/funkensturm/ember-local-storage/pull/19 and master provides an ember-data adapter.

See [Adapter & Serializer](https://github.com/funkensturm/ember-local-storage#adapter--serializer) in the README.

**Comment by fsmanuel** [comment]
@sunil-shrestha I'll investigate into the poor performance but I think an adapter is what you want.

**Comment by fsmanuel** [comment]
@sunil-shrestha I added documentation for the models: https://github.com/funkensturm/ember-local-storage#model

**Comment by sunil-shrestha** [comment]
Thanks ! I will try it then.

**Comment by fsmanuel** [comment]
@sunil-shrestha I'll release a new version if it works for you.
