### ISSUE TITLE
Models not persisting to local storage

### ISSUE THREAD

**Issue by CodingItWrong** [funkensturm/ember-local-storage#284]
I'm attempting to get `ember-local-storage` working to store my Ember Data models locally, but the data doesn't seem to be persisting. I've created a demo project here:

https://github.com/CodingItWrong/ember-local-storage-troubleshooting

I believe the adapter and serializer are set up according to what the readme describes, but I don't see any entries in my browser's Local Storage:

<img width="1087" alt="screen shot 2018-05-07 at 11 29 11 am" src="https://user-images.githubusercontent.com/15832198/39710122-e50ffe82-51e9-11e8-8979-2046e9f01629.png">

And when I reload the app data isn't preserved.

Am I missing something obvious, or could there be a bug occurring in Ember 3.1.3?

**Comment by CodingItWrong** [comment]
I was missing something obvious; I wasn’t calling `.save()` on the record. Carry on!

**Comment by fsmanuel** [comment]
@CodingItWrong great that it works now!
