### ISSUE TITLE
Ember 3.3 Use ember-copy addon instead of copy method and Copyable mixin. [deprecation id: ember-runtime.deprecate-copy-copyable]

### ISSUE THREAD

**Issue by ShenglinGuo** [funkensturm/ember-local-storage#286]
Copy method used in storage.js has been deprecated after ember 3.3 ?

ember-local-storage/addon/mixins/storage.js

**Comment by lsg-richard** [comment]
Correct. It should be trivial to switch to https://github.com/emberjs/ember-copy instead which provides identical functionality in an add-on.

**Comment by fsmanuel** [comment]
@ShenglinGuo @lsg-richard I released `1.4.2` with the fix.
