### ISSUE TITLE
Q: StorageObject not working.

### ISSUE THREAD

**Issue by AdminDev826** [funkensturm/ember-local-storage#294]
I have created StorageObject for `sobject`
```
s_object: storageFor('sobject'),
...
this.set('s_object', {'a','b'}); ----> It seems not saved to storage.
```

**Comment by richard-viney** [comment]
The `set()` call there is replacing the entire value of `this.s_object`. Try calling `set()` or `setProperties()` on the storage object instead, e.g. `this.s_object.setProperties({ a: 'value', b: 'value2' }).

**Comment by fsmanuel** [comment]
@AdminDev826 I'm closing this. If you still need help please reopen the issue.
