### ISSUE TITLE
Package doesn't follow semver

### ISSUE THREAD

**Issue by elwayman02** [funkensturm/ember-local-storage#30]
Moving from 0.0.6 to 0.0.7/8 introduced Ember-Data 1.13.5 and breaking changes to this library for apps that cannot support the sweeping upgrade pains of the newer E-D versions.  The latest versions should have at least been 0.1.0, and moving forward it would be nice to have semver followed so we avoid these nasty surprises. :)

**Comment by fsmanuel** [comment]
@elwayman02 you are totally right. I was planing to release it as 1.0.0 but somehow didn't do it. Sorry for the inconvenience. I'm curious how the Ember-Data dependency breaks the app. I didn't add it as a npm dependency and thought that everyone can decide to use the new adapter and install Ember-Data.
Thanks for the hint. I'll have semver in mind when it comes to a new release.

**Comment by fsmanuel** [comment]
@elwayman02 I released 0.0.9 that should fix the problem. With ember-data < 1.13.0 you can use everything except the serializer & adapter.

**Comment by elwayman02** [comment]
Yea sorry for not responding...it was the use of non-existent Adapter/Serializer objects that was breaking projects not on Ember-Data 1.13+
