### ISSUE TITLE
Can't use this without ember-data on 3.7

### ISSUE THREAD

**Issue by robclancy** [funkensturm/ember-local-storage#300]
I don't know what changed but now I'm getting and import error from the initializer.

If anyone else runs into this issue you can simply workaround it with `ember g initializer local-storage-adapter`.

**Comment by fsmanuel** [comment]
Hey @robclancy thanks for the feedback and the workaround. I'll have a look at it.

**Comment by fsmanuel** [comment]
@robclancy can you post the import error? Would be helpful!

**Comment by robclancy** [comment]
Seems to be fixed with last update.
