### ISSUE TITLE
ember-data support removed when used by ember-twiddle

### ISSUE THREAD

**Issue by sukima** [funkensturm/ember-local-storage#302]
The addon [removes all the ember-data support modules](https://github.com/funkensturm/ember-local-storage/blob/eece52d4c5ea1b528ed3e5dfc9eaa8c56be6fd3e/index.js#L112) which makes sense for projects that do not have ember-data as a dependency.

Unfortunately the checking logic depends on a `package.json` which does not exist in an ember-twiddle project.

I would like to suggest that there be a config option to disable the pruning logic that way in a twiddle the following `twiddle.json` can enable the ember-data support:

```json
{
  "version": "0.15.1",
  "EmberENV": {
    "FEATURES": {}
  },
  "ENV": {
    "ember-local-storage": {
      "includeEmberDataSupport": true
    }
  },
  "options": {
    "use_pods": false,
    "enable-testing": false
  },
  "dependencies": {
    "jquery": "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js",
    "ember": "3.4.3",
    "ember-template-compiler": "3.4.3",
    "ember-testing": "3.4.3"
  },
  "addons": {
    "ember-data": "3.4.2",
    "ember-local-storage": "1.5.0"
  }
}
```

**Comment by fsmanuel** [comment]
@sukima Released as `1.6.0`
