### ISSUE TITLE
[Feature Request] Sets

### ISSUE THREAD

**Issue by jmonster** [funkensturm/ember-local-storage#305]
I just discovered _and love_ this addon. I'm successfully using the array component ... but then realized I actually need uniqueness and have application logic to ensure just that. However, my app could/will be simpler when a Set type becomes available 😬

**Comment by fsmanuel** [comment]
What are the values you store in the array?

**Comment by jmonster** [comment]
ids as strings (and then I have a computed property that observes the storage array and fetches the actual records)

**Comment by fsmanuel** [comment]
@jmonster If you use `.addObject('123')` it should check for uniqueness. See the docs: https://www.emberjs.com/api/ember/3.7/classes/MutableArray/methods/addObject?anchor=addObject

> obj * object to add, if not already present

**Comment by jmonster** [comment]
Welp... thank you so much haha :) I wonder if that makes adding an O(n) operation then? Or if a Set is maintained internally to track uniqueness?

Might be cool to add a Set that just remaps push to add? That way you could still get some of the other Set properties (most importantly for me, O(1) lookups)

Anyway, thank you kindly! Much appreciated.

**Comment by fsmanuel** [comment]
Closing this for now. If you are interested in implementing a `Set` you are welcome to reopen it.
