### ISSUE TITLE
Ember 3.4.4 Models Not Setting On Browser Reload

### ISSUE THREAD

**Issue by jrock2004** [funkensturm/ember-local-storage#309]
Been using this add-on for awhile and I have encountered an issue during an ember and addon upgrade that I need some help with. On an adapter for a model I have set the following

```
export { default } from 'ember-local-storage/adapters/local';
```
Looking at local storage I seem the model and I see the relationship just fine
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/655716/56257256-a66dfe80-6099-11e9-8f56-ff7b963a6047.png">

Everything is working until I reload the page. Before the upgrade the models would load just fine. But now the models load but values are missing. Its not being removed from local storage as I see it. Not sure what additional info you may need for this. It seems like the model types are all of the sudden unknown

<img width="420" alt="image" src="https://user-images.githubusercontent.com/655716/56257434-301dcc00-609a-11e9-93d3-c9543d8b8afb.png">

**Update 1:**

So I went back to ember 2.18 and kept newest version of ember local storage and it works. I upgraded ember data version by version and found that what broke reloading is `3.2.2`. Going to try to get a couple of twiddles with examples

![image](https://user-images.githubusercontent.com/655716/56299132-6f333800-6101-11e9-9186-81072b0703af.png)

**Comment by fsmanuel** [comment]
@jrock2004 Thanks for reporting! I'll take a look in the next days. The problems were introduced with 3.4, right?

**Comment by jrock2004** [comment]
@fsmanuel not sure if it was exactly 3.4 it started.

**Comment by jrock2004** [comment]
Seems like ember-data `3.2.2` is where the issue began

**Comment by fsmanuel** [comment]
@jrock2004 could you solve the problem?

**Comment by fsmanuel** [comment]
Because of inactivity I'm closing this. Feel free to reopen.
