### ISSUE TITLE
Doesn't work without Ember Data

### ISSUE THREAD

**Issue by SebastianEdwards** [funkensturm/ember-local-storage#31]
Versions 0.0.7 and on won't work for those who don't use Ember Data.

Errors at the following line since `Adapter` is undefined - https://github.com/funkensturm/ember-local-storage/blob/master/addon/adapters/adapter.js#L16

**Comment by fsmanuel** [comment]
@SebastianEdwards thanks for reporting. I released 0.0.9 that should fix the problem.

**Comment by fsmanuel** [comment]
reopen if you run into problems with 0.0.9
