### ISSUE TITLE
Support for peekAll and peekRecord

### ISSUE THREAD

**Issue by jrock2004** [funkensturm/ember-local-storage#314]
Is there any plan on supporting peekRecord and All?

**Comment by fsmanuel** [comment]
Hey @jrock2004 interesting question!
As `peekAll` and `peekRecord` are ember-data methods on the store they are available for you.
The adapter doesn't need to support it as it only operates on the internal store/cache.

If you think that this fact needs to be documented I'm happy to accept a PR.

**Comment by jrock2004** [comment]
Where I was confused was due to understanding on page reload, when the addon takes the localstorage and loads the data model. 

So on reload I have to do `store.findAll` somewhere to get the cache switched to ember models. then after that peekRecords and such work. Or am I missing this again?

**Comment by fsmanuel** [comment]
Hey @jrock2004, ok now I got your question. So in general you can always just use `findAll` and `findRecord` as the adapter is configured to do a background reload and will always first return the cached records from the store. As we only access the localStorage and don't have to talk to a server the overhead to fetch the new data is minimal.
Did that help with the confusion?
