### ISSUE TITLE
desc.get is not a function TypeError: desc.get is not a function

### ISSUE THREAD

**Issue by TNAJanssen** [funkensturm/ember-local-storage#32]
When using virtual property, you wil get this error

    import StorageObject from 'ember-local-storage/local/object';
    
    export default StorageObject.extend({
      storageKey: 'client-intake',
      initialContent: {
    
        step1Valid: function() {
          return false;
        }.property(),
      }
    });

**Comment by fsmanuel** [comment]
@TNAJanssen you can not define a computed property in POJOs.
What you can do is:

```js
import Ember from 'ember';
import StorageObject from 'ember-local-storage/local/object';

const Settings = StorageObject.extend({
  storageKey: 'settings',
  initialContent: {
    welcomeMessageSeen: false
  },

  hasSeen: Ember.computed('welcomeMessageSeen', function() {
    return this.get('welcomeMessageSeen');
  })
});

export default Ember.Controller.extend({
  settings: Settings.create(),

  actions: {
    toggle: function() {
      this.get('settings').toggleProperty('welcomeMessageSeen');
    }
  }
});
```

**Comment by fsmanuel** [comment]
@TNAJanssen can I close the issue?

**Comment by TNAJanssen** [comment]
@fsmanuel  sorry! Yes you can! Thanks!
