### ISSUE TITLE
DEPRECATION: The ... computed property was just overrider - error while using Ember.set function on the storageFor computed property 

### ISSUE THREAD

**Issue by segemun** [funkensturm/ember-local-storage#322]
Ember CLI version: 3.20.0

`items: storageFor('items')`
`set(this, 'items', {});`

Then I get an error:
DEPRECATION: The ...#items computed property was just overriden.

**Comment by CvX** [comment]
Setting `this.items` to `{}` removes the storage property.

Take a look at the readme for examples on how to clear a storage object:

https://github.com/funkensturm/ember-local-storage#object

```js
this.get('stats').clear();
// or
// this.get('stats').reset();
// this.set('stats.counter', 0);
```

**Comment by segemun** [comment]
Thanks.
What is the right way to rewrite items value from the code?

`items: storageFor('items')`
`const items = {test: 1, test: 2}`
`set(this, 'items', items)`

**Comment by segemun** [comment]
As I understood, I can use such approach:
`items: storageFor('items')`
`const items = {test: 1, test: 2}`
`set(this, 'items.test', 1)`
`set(this, 'items._test', 2)`

Thanks

**Comment by fsmanuel** [comment]
@segemun the sotrage is a proxy so in new versions of ember you can also do that:

```js
items: storageFor('items')

this.items.set('test', 1)
```
