### ISSUE TITLE
Is this addon expected to work with Ember Octane?

### ISSUE THREAD

**Issue by jking6884** [funkensturm/ember-local-storage#325]
I am seeing an issue with getting this addon to work with Ember 3.26, but it was previously working in 3.11.

**Comment by fsmanuel** [comment]
@jking6884 It's supposed to work. I'm using it with `3.24.0`. What are the issues?

**Comment by jking6884** [comment]
There seems to be several problems, I think.

![image](https://user-images.githubusercontent.com/4825257/116733175-c723fb00-a9b9-11eb-8ca8-d5fd44ec6935.png)

This computed that is returned from `storageFor` never seems to fire the way it is set up.  I was thinking this was potentially because of the fact that the get/set functionality is not the same in the native classes in Octane.  At any rate, it doesn't seem to fire ever, so the storage create method isn't called either.  However, I also found that if I tweaked the way that the logic worked (I create an in-repo-addon with ember-local-storge and changed things to test), the create method was also not getting the proper value of `this`.  So I had to pass in the context from the controller when calling storageFor.

The computed property also doesn't seem to be firing when setting values.

![image](https://user-images.githubusercontent.com/4825257/116732459-d3f41f00-a9b8-11eb-8805-442fe6a37db6.png)

![image](https://user-images.githubusercontent.com/4825257/116732503-e40bfe80-a9b8-11eb-88b6-980549fcab09.png)

**Comment by fsmanuel** [comment]
You can use it like that:

```js
import { storageFor } from "ember-local-storage";

export default class extends Controller {
  @storageFor('role') roleStorage;

  doSomething() {
    this.roleStorage.get('someKey');
  }
}
```

**Comment by jking6884** [comment]
@fsmanuel I have confirmed that it is indeed working when using it as a decorator.  Thanks for that clarification.

I think it would be a great idea to document this in the readme as it is currently not very clear how this addon should be used in the context of native classes with Octane.

**Comment by fsmanuel** [comment]
@jking6884 good point. Will add documentation for native classes in the next days.
