### ISSUE TITLE
Ember 4 compatibility

### ISSUE THREAD

**Issue by pago** [funkensturm/ember-local-storage#340]
We are in the process of trying to upgrade our Ember application to v4.
After upgrading, running the application fails due to `ember-local-storage` importing `deprecate` from `@ember/application/deprecations` in `addon/helpers/storage.js`, which does not exist.

This issue has already been fixed in this PR: https://github.com/funkensturm/ember-local-storage/pull/339/files
However, the currently released v2.0.0 of this addon seems to not include that change.

My assumption would be that the issue could be fixed by releasing the current `master` branch.

**Comment by fsmanuel** [comment]
Hey @pago, thanks for reporting. I'll release a new version with the deprecation fix.

**Comment by fsmanuel** [comment]
@pago `v2.0.1` is released. Please let me know if you run in any other problems.

**Comment by pago** [comment]
Thank you for the fast resolution. Works like a charm! We've been able to upgrade our app to Ember 4.
