### ISSUE TITLE
Records added with store.push() aren't persisted in LS

### ISSUE THREAD

**Issue by Ramblurr** [funkensturm/ember-local-storage#41]
Coming from [locks/ember-localstorage-adapter](https://github.com/locks/ember-localstorage-adapter), I'm not sure how to use the StorageObject class.

Do I have one per application? Or do I need one for each model I want to persist in LS?

**Comment by fsmanuel** [comment]
Hey @Ramblurr what do you want to achieve? If you need an adapter like ember-localstorage-adapter read [Adapter & Serializer](https://github.com/funkensturm/ember-local-storage#adapter--serializer) in the readme.

`StorageObject` is more like an object where you have one instance that persists on changes to LS. Like settings. It's not an ember-data model just an object.

**Comment by Ramblurr** [comment]
@fsmanuel I understand now, I didn't realize that there were two different ways to use the addon.

Is there no way to configure the LS key when using the ember data adapter?

**Comment by Ramblurr** [comment]
Could the issue be that I'm pushing data into the store with store.push() rather than using createRecord or something. Because the adapter's `_addToIndex` method is never being called.

**Comment by fsmanuel** [comment]
@Ramblurr yes. You need to go through the adapter.

**Comment by Ramblurr** [comment]
@fsmanuel When I store.push() records, a PATCH request is started. So in `_handlePATCHRequest` we can add the record to the index if it doesn't exist. Something [like this](https://github.com/Ramblurr/ember-local-storage/commit/f786b20c06807d41033865703b0724bb7fb72b50). What do you think?

I need this feature, because my Ember app is fetching data from a server, and storing it in LS. (Rather than creating new data fresh in the app).

**Comment by fsmanuel** [comment]
@Ramblurr sure thing! that is a great idea. can you open a PR and add a test. Something like the [create test](https://github.com/funkensturm/ember-local-storage/blob/master/tests/unit/models/post-test.js#L37).

**Comment by fsmanuel** [comment]
@Ramblurr Now you can just add the key to the index. See my last [commit](https://github.com/funkensturm/ember-local-storage/commit/7042d8e54b43b0f406b493b22f78f2610c52c330#diff-290ffea09596a16e3b2b43264137ccf8R307)

**Comment by Ramblurr** [comment]
@fsmanuel great, thanks!

So now the index-XXX key is being created when I store.push() models. But when I refresh the page, ember data isn't being repopulated with the items in the store.

This is what I'm doing:

1. push() models to ember data
2. observe in Ember inspector that the data exists
3. observe that the data exists in LS 
4. refresh the page, run a findAll()
5. the Ember inspector shows ember-data doesn't have any data in it, but LS still has the data and the indices.

Any idea what's going on here?

**Comment by fsmanuel** [comment]
@Ramblurr perfect. thanks for the bug fix.

**Comment by fsmanuel** [comment]
@Ramblurr do need help with the test? I can write one and you PR the fix?

**Comment by fsmanuel** [comment]
@Ramblurr I'll cut a new release as soon as we have the fix merged.
