### ISSUE TITLE
Querying on camelCase poperties

### ISSUE THREAD

**Issue by Ramblurr** [funkensturm/ember-local-storage#42]
Not sure if this is a bug or just an incorrect way of doing things.

In my model I define a property like so `fooBar = DS.attr()`. Later when I want to query against it I write `store.query('my-model', {filter: { fooBar: value } }`

Result: it never works, I always receive an empty list.

Debugging the adapter I see now that it is expecting the dasherized property, `foo-bar` to be passed as the query. This is strange and inconvenient as everywhere else I refer to it via `myModel.get('fooBar')`.

Thoughts? Is this a bug?

**Comment by fsmanuel** [comment]
@Ramblurr i run into a similar problem with ember data: https://github.com/emberjs/data/pull/3910
will check what i can do about it. it's a bug or at least it's inconvenient and should be changed.

**Comment by Ramblurr** [comment]
On a related note, what's the difference between `{filter: { fooBar: value } }` vs `{ fooBar: value }`?

**Comment by fsmanuel** [comment]
@Ramblurr only `filter:` works. See the [guides](http://guides.emberjs.com/v2.1.0/models/finding-records/#toc_querying-for-multiple-records) and the [JSON API Spec](http://jsonapi.org/format/#fetching-filtering). I want to stay as close to the Spec as possible.

Somewhat related do you use the `attrs` hash in your serializers or how do you transform the data from the server for the `store.push()`?

**Comment by Ramblurr** [comment]
Thanks @fsmanuel . I'm not using the `attrs` hash.

To transform the data from my server into valid JSONAPI objects, I've added a `normalizeMyServerArrayPayload()` method to my serializer, then I do something like:

```js
  _pushServerPayload: function(modelName, response) {
    var serializer = this.store.serializerFor(modelName);
    var modelClass = this.store.modelFor(modelName);
    var normalized = serializer.normalizeMyServerArrayPayload(this.store, modelClass, response);

    this.store.push(normalized)
}
```

`normalizeMyServerArrayPayload()` transforms the server's response into a JSONAPI object.

It's not ideal, but its working.
