### ISSUE TITLE
queryRecord returns `undefined` when no result is found.. triggers Ember Assertion

### ISSUE THREAD

**Issue by Ramblurr** [funkensturm/ember-local-storage#44]
in adapter.js in the `queryRecord` method, there exists this code: 

```
      return records.then(function (result) {
        return { data: result.data[0] };
      });
```

Now, if there was no result found `records` is a `{data: Array[0]}` and `result.data[0]` returns `undefined`. 

Later Ember asserts with the error:

> Assertion Failed: normalizeResponse must return a valid JSON API document:
>     * data must be null, an object, or an array

([from here](https://github.com/emberjs/data/blob/96d211b9f0f7e1525aaf96059cc1d6239a7588c6/packages/ember-data/lib/system/store/serializer-response.js#L78))

`queryRecord` should return `null` instead of `undefined`

**Comment by fsmanuel** [comment]
@Ramblurr makes sense. Thanks for reporting.

**Comment by Ramblurr** [comment]
Making a PR. (nice response time, haha)

**Comment by fsmanuel** [comment]
@Ramblurr great! you battle prove the adapter!

**Comment by fsmanuel** [comment]
@Ramblurr I'll release `0.1.1` now. See the [changelog](https://github.com/funkensturm/ember-local-storage/blob/master/CHANGELOG.md#011). `queryRecord()` will return an empty array until ember-data is fixed. I guess the best is to test with `Ember.isEmpty()` if there is a record.

related https://github.com/emberjs/data/issues/3790

**Comment by Ramblurr** [comment]
This was fixed in ember-data 2.2.1 ([source](https://github.com/emberjs/data/issues/3790#issuecomment-174962777))

**Comment by fsmanuel** [comment]
@Ramblurr is it just an information or are any steps required?

**Comment by Ramblurr** [comment]
Just information :) We need to test to make sure its working as expected still.
