### ISSUE TITLE
Add a JSON object to the storageObject

### ISSUE THREAD

**Issue by Jordan4jc** [funkensturm/ember-local-storage#49]
How would I go about adding a JSON object to the local storage using the `storageObject`?

When I try adding it like I normally would make a JSON object it's all empty.

Or is this not how local storage is intended to be used?

**Comment by Jordan4jc** [comment]
I was able to get this working by setting the object I wanted to set in the local storage to an empty object to begin with

**Comment by fsmanuel** [comment]
@Jordan4jc Have you tried using `initialContent` or `setProperties`?
