### ISSUE TITLE
Having trouble using in a service

### ISSUE THREAD

**Issue by Jordan4jc** [funkensturm/ember-local-storage#52]
I'm attempting to use a service to access data from the local storage since I'll be saving a json object with user info. But I can't seem to get it to work.

In my service I am attempting to set a property for the users id like so

```
import Ember from 'ember';
import LocalUser from 'bidr/models/user-local';

export default Ember.Service.extend({
	localUser: LocalUser.create(),
	user_id: this.get('localUser').get('content').user.id
});
```

But in my component where I am attempting to access this property I am getting `this.get is not a function` in the console as an error.

Is there some other setup I need to do instead to get this to work in the service?

**Comment by fsmanuel** [comment]
You should use an alias:

```js
import Ember from 'ember';
import LocalUser from 'bidr/models/user-local';

const {
  computed: {
    alias
  }
} = Ember;

export default Ember.Service.extend({
    localUser: LocalUser.create(),
    user_id: alias('localUser.user.id')
});
```

**Comment by Jordan4jc** [comment]
Cool that worked thanks!
