### ISSUE TITLE
addObject storing null values

### ISSUE THREAD

**Issue by jigneshchudasama05** [funkensturm/ember-local-storage#6]
When i try to add new object on click without refreshing page in localstorage then its storing the existing value and setting null for the other data exiting in that, and when i repeat this after refreshing the page its working properly.

**Comment by fsmanuel** [comment]
@jigneshchudasama05 thanks for reporting. Can you give me more details on your setup (addon version and ember version) and how you setup the localStorageArray?

**Comment by jigneshchudasama05** [comment]
@fsmanuel 
"ember": "1.11.1",
"ember-local-storage": "0.0.4"

// Adding object to localstorage
this.get('localSubmissions').addObject({ //adding object to localstorage
    user_data: user, //user data
    feedback_template_id: _this.get('client.feedback_template.id'), // template data
    client_id: _this.get('client.id'), //client data
    feedbacks_data: _this.get('validFeedbacks') //feedbacks data
});


// Removing object from localstorage once its get stored on db

syncSubmissions: function() {

    if (!("onLine" in navigator && !navigator.onLine)) { //Checking if browser is online or not
        var _this = this,
            submissions = this.get('localSubmissions'), //Retrieving data from localstorage
            submission = this.get('localSubmissions.firstObject'); //Retrieving firstObject out of it

        _this.store.createRecord('submission', submission).save().then(function() { //saving the current object to db
            _this.get('localSubmissions').removeObject(submission);// removing current object from localstorage
            if(submissions.get('length') > 0) {
                _this.send('syncSubmissions'); //recursive call
            }
        });
    }

}

**Comment by fsmanuel** [comment]
@jigneshchudasama05 can you also provide the json from localStorage when it fails and when it works?

**Comment by fsmanuel** [comment]
@jigneshchudasama05 any news? maybe the `0.0.5` release fixed your issue?

**Comment by fsmanuel** [comment]
@jigneshchudasama05 i'm closing. we can reopen if there are still problems.
