### ISSUE TITLE
Could not find module `ember-local-storage/adapters/adapter`

### ISSUE THREAD

**Issue by Arkham** [funkensturm/ember-local-storage#61]
Hello there, 

I was following the readme and trying to use the adapter and the serializer and I got this error:

![screen shot 2016-01-14 at 12 55 55](https://cloud.githubusercontent.com/assets/62895/12324916/2e84aeca-babe-11e5-951b-cbbdd35ea143.png)

I'm using:
* ember-local-storage 0.1.3
* ember-cli 2.2.0-beta6
* ember 2.2.0
* ember-data 2.3.1
* jquery 1.11.3

**Comment by fsmanuel** [comment]
@Arkham Have you restarted the server after installing the addon?

**Comment by fsmanuel** [comment]
Or is there any other error before that? I'll setup a new app with ember-cli 2.2.0-beta6 to test.

**Comment by fsmanuel** [comment]
@Arkham got it. I was checking for `ember-data` on bower. Now that `ember-data` is an addon it no longer works. Will release a new version in some minutes.

**Comment by Arkham** [comment]
@fsmanuel yes, nombomed and restarted. Thanks for taking a look!

**Comment by fsmanuel** [comment]
@Arkham I released `0.1.5`.

**Comment by Arkham** [comment]
Thanks so much! :+1:

**Comment by fsmanuel** [comment]
Thanks for reporting!
