### ISSUE TITLE
reset method

### ISSUE THREAD

**Issue by miguelcobain** [funkensturm/ember-local-storage#7]
It might make sense to add a `reset()` method to `StorageObject` that basically does `this.setProperties(this.initialContent);`.

What do you think?

**Comment by fsmanuel** [comment]
Sounds good to me. Do you mind open a PR?

**Comment by fsmanuel** [comment]
@miguelcobain thanks again for both the cli update and the new feature. much obliged.

**Comment by miguelcobain** [comment]
No problem, mate. :boat:
