### ISSUE TITLE
How to get started using local storage? Any compelte examples?

### ISSUE THREAD

**Issue by Levino** [funkensturm/ember-local-storage#70]
Does anyone have a simple example where I can understand how the routes - components - storage adapter is connected?

I created a "user" model, a "profile" route and I get a 404 in the console that "localhost:4200/users" cant be found.

Code is here: https://github.com/Levino/steuertools/tree/1268f966131f19c26f215dcfd137c55d549c2474

I just want localhost:4200/profile to render...

I know this is very basic, but the guides are so bad that I am close to throwing the towel with emberjs, so please someone help me out.

**Comment by fsmanuel** [comment]
@Levino there are different concepts and it depends on what you want.

1. You can use `storageFor` to work with an object or array that persists to localStorage if changed.
2. You can use the localStorage adapter to use ember-data models.

I guess you want the later one.

Run `ember g adapter application` and `ember g serializer application` then follow the instruction in the [readme](https://github.com/funkensturm/ember-local-storage#adapter--serializer).

```js
// app/adapters/application.js
export { default } from 'ember-local-storage/adapters/adapter';

// app/serializers/application.js
export { default } from 'ember-local-storage/serializers/serializer';
```

That should make it work. Hope you don't throw the towel as germany needs more ember devs!

**Comment by fsmanuel** [comment]
@Levino I'm closing this. You can reopen if you need more help.

**Comment by Levino** [comment]
Dear @fsmanuel Thanks so far. It helped indeed and I am one step further. Don't have too much time to work on the project though.

Thanks again for this valuable feedback and sorry for not closing myself earlier.
