### ISSUE TITLE
Can't get a record from the local storage

### ISSUE THREAD

**Issue by Jordan4jc** [funkensturm/ember-local-storage#72]
I can't seem to get at the record I have saved in local storage with `findRecord`

I have a route that requires someone to authenticate with my backend using a key, that calls a normal ajax action that I take the response and store in local storage using the default local storage adapter

    Ember.$.ajax({
	type: 'get',
	dataType: 'json',
	url: `http://***/api/users/url/${params.short_url}?key=${ENV.APP.api_key}`
    }).then((response)=>{
	var user = this.store.createRecord('user',response);
	user.set('id',1);
	user.save().then(()=>{
	    this.transitionTo('index');
        });
    });

Then I'm attempting to make another ajax call in another route using the `user_id` property of that saved user in local storage like so

    var user = this.store.findRecord('user',1).get('user-name');

Maybe I'm just doing this wrong but when I console.log that it comes as undefined. How do I get the user out of local storage to grab a specific property from it?

**Comment by fsmanuel** [comment]
Can you check the localStorage in the developer tools? Is the record in there?
`findRecord` returns a promise so try `.then(function(user) { return user.get('user-name') });`
