### ISSUE TITLE
Inject local storage model to be used anywhere

### ISSUE THREAD

**Issue by Jordan4jc** [funkensturm/ember-local-storage#75]
This may be outside the scope of this addon but I am using the adapter and serializer to store user info in local storage. This gets populated with normal ajax requests that create and save records into the local storage store.

What I need is to be able to use this user record in local storage (there will only ever be one at a time) in computed properties and to display in templates.

I'm just not sure on what approach I need to take. Most importantly it needs to notify computes and observables that properties on the user record have changed so they can recompute etc. Seems obvious but I was previously using local storage as a custom service but updating the local storage object did not notify computes of property changes.

**Comment by fsmanuel** [comment]
@Jordan4jc I'll try to write you on slack tomorrow. we can post the solution here but I have to know more details.

**Comment by fsmanuel** [comment]
@Jordan4jc I would go for a session service:

```js
// services/session.js
import Ember from 'ember';

const {
  computed,
  isEmpty
} = Ember;

export default Ember.Service.extend({
  userId: null,
  store: Ember.inject.service(),
  
  user: computed('userId', function() {
    let id = this.get('userId');
    
    if (!isEmpty(id)) {
      return this.store.findRecord('user', id);
    }
  })
});
```

After you fetched the user via ajax and created and saved the user to local storage you set the id on the service:

```js
export default Ember.Route.extend({
  session: Ember.inject.service(),

  beforeModel() {
    // fetch user
    // create and save user
    this.set('session.userId', userId);
  }
});
```

Now it should be possible to inject the session service where ever you need it and make your properties dependent on them:

```js
const {
  computed,
  computed: {
    alias
  }
  isEmpty
} = Ember;

export default Ember.Component.extend({
  session: Ember.inject.service(),

  userName: computed('session.user.name', function() {
    return this.get('session.user.name');
  }),
  // or
  name: alias('session.user.name')
});
```

Hope that helps.

**Comment by fsmanuel** [comment]
@Jordan4jc can I close this?

**Comment by Jordan4jc** [comment]
I believe so, everything looks like it's functioning the way we intended, thanks!
