### ISSUE TITLE
Reloading hasMany associations

### ISSUE THREAD

**Issue by juni0r** [funkensturm/ember-local-storage#77]
Hi,

using the latest Ember Data (2.3.0) models in a hasMany associations are duplicated if the parent model is reloaded.

I created an [example project](https://github.com/juni0r/ember-local-storage-has-many) with a test reproducing the issue.

**Comment by fsmanuel** [comment]
@juni0r I ran into a similar problem with a `hasMany` association. I'll look into it. Thanks for the test repo. That'll be a good starting point.

**Comment by fsmanuel** [comment]
@juni0r I looked into your problem and figured the tests are failing because you don't save the comments.

That one works:
```js
store.createRecord('comment', { post, text: 'I agree' }).save();
store.createRecord('comment', { post, text: 'I disagree' }).save();

post.save()
.then(post => {
  assert.equal(get(post, 'comments.length'), 2);

  store.find('post', post.get('id'))
  .then(model => {
    assert.equal(get(model, 'comments.length'), 2, 'model.comments');
  });
});
```

**Comment by juni0r** [comment]
@fsmanuel Thanks for looking into this! I'm fairly new to Ember Data and sometimes its behavior still puzzles me. I assumed that when I create child records, they get saved automatically with the parent record, especially since the child records get embedded with the local storage adapter.

I did some research on the topic and came across the EmbeddedRecordsMixin. From what I read, it does exactly what I described above, but apparently it doesn't.

I tried:

```js
// app/serializers/application.js

import DS from 'ember-data';
import Serializer from 'ember-local-storage/serializers/serializer';

export default Serializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    comments: { embedded: 'always' },
  },
});
```

Now what happens is (again omitting the `save()` call) that the comments aren't duplicated but disappear when reloading. This is still not what I wish for, but at least the result is more consistent, since the records are not persisted when they haven't been saved explicitely. 

Now I'm still not familiar enough with the concepts of Ember Data to tell if the EmbeddedRecordsMixin is even compatible with the local storage serializer. But if it is, would it make sense to include it by default. Just wondering.

**Comment by fsmanuel** [comment]
@juni0r It is puzzling sometimes, for me too.

Have a look at the [serializer](https://github.com/funkensturm/ember-local-storage/blob/master/addon/serializers/serializer.js#L9) I just let the `hasMany` relationships be serialized. I guess this is the root of the confusion. Here are the [docs](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html#method__shouldSerializeHasMany) for 
`_shouldSerializeHasMany`. The signature gives us more context and I guess we can figure out if the relations are already saved or not and return `true` if they are saved.

I might give it a try on the weekend. If you have time you can play with it and submit a PR.
If the behavior is consistent we can try to make a autoSave work from the `hasMany` side.
